'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Properties


	''' <summary>
	'''   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	''' </summary>
	' StronglyTypedResourceBuilder generó automáticamente esta clase
	' a través de una herramienta como ResGen o Visual Studio.
	' Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	' con la opción /str o recompile su proyecto de VS.
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")> _
	<System.Diagnostics.DebuggerNonUserCodeAttribute> _
	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	Public Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("CapaPresentacion.Properties.Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		'''   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Public Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property agregar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("agregar", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property agregar_producto() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("agregar_producto", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property categorias() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("categorias", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property clientes() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("clientes", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property editar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("editar", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property eliminar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("eliminar", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property eliminar_producto() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("eliminar_producto", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property email() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("email", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property empleados() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("empleados", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property entregado() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("entregado", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property favicon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("favicon", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property Floppy_disk_512() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Floppy_disk-512", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property fondo_logo() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("fondo-logo", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property inicio() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("inicio", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property marcarEntregadoPendiente() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("marcarEntregadoPendiente", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property pedidos() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("pedidos", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property pendiente() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("pendiente", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property productos() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("productos", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property reportes() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("reportes", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property transporte() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("transporte", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property twitter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("twitter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		''' <summary>
		'''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		''' </summary>
		Public Shared ReadOnly Property youtube() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("youtube", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property
	End Class
End Namespace
